Get cardinal working on Mac M2 Architecture
Signed-off-by: Sarah Allen <sarmth@icloud.com>

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -60,6 +60,7 @@ install_submodules_manually() {
             fi
             cd "$CWD/$LAST"
             echo "Installing $item"
+            git config --global --add safe.directory "$CWD/$LAST"
             git init .
             git remote add origin $item
             res=$(git pull origin master 2>&1)
@@ -79,7 +80,7 @@ install_modules () {
         git submodule init
         git submodule update
     fi
-    if [[ ! -d "$CWD/vendor/crashoz" ]]
+    if [[ ! -d "$CWD/vendor/microsoft" ]]
     then
         echo "Unable to auto-install using GIT, trying another route."
         install_submodules_manually
@@ -117,11 +118,22 @@ then
     /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER='/usr/bin/clang' -DCMAKE_CXX_COMPILER='/usr/bin/clang++' -DCMAKE_MAKE_PROGRAM='/Users/sarahjabado/.vscode/extensions/powertech.powercpp-23.2.24/thirdparty/bin/ninja' -S/Users/sarahjabado/development/cardinal_c++ -B/Users/sarahjabado/development/cardinal_c++/build -G Ninja
 elif [[ "$1" = "build" ]]
 then
+    git config --global --add safe.directory '*'
     install_modules
     CWD=$(pwd)
-    if [[ ! -f "$CWD/vendor/crashoz/uuid_v4/build/Makefile" ]]
+    if [[ ! -f "$CWD/vendor/microsoft/GSL/build/Makefile" ]]
     then
-        cd "$CWD/vendor/crashoz/uuid_v4/"
+        cd "$CWD/vendor/microsoft/GSL/"
+        mkdir build
+        cd build
+        cmake ..
+        make
+        make install || echo "Cannot install Microsoft GSL on the system."
+        cd "$CWD"
+    fi
+    if [[ ! -f "$CWD/vendor/mariusbancila/stduuid/build/Makefile" ]]
+    then
+        cd "$CWD/vendor/mariusbancila/stduuid/"
         mkdir build
         cd build
         cmake ..
